// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOqFdCftAcLo095PrfAPpz_IaTsEdzkeQ',
    appId: '1:555705912730:web:6d0584e39b013ddabffe23',
    messagingSenderId: '555705912730',
    projectId: 'healthmonitoring-90af9',
    authDomain: 'healthmonitoring-90af9.firebaseapp.com',
    storageBucket: 'healthmonitoring-90af9.firebasestorage.app',
    measurementId: 'G-C0NNZCGER4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWfqqukgdoU75oGqK52bbACAWIquO6STE',
    appId: '1:555705912730:android:1d32bf28e1c4371fbffe23',
    messagingSenderId: '555705912730',
    projectId: 'healthmonitoring-90af9',
    storageBucket: 'healthmonitoring-90af9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzAZj8Kbj74nycnTiiRHRmlZBNRILy5kE',
    appId: '1:555705912730:ios:f5c0a0d2b096de63bffe23',
    messagingSenderId: '555705912730',
    projectId: 'healthmonitoring-90af9',
    storageBucket: 'healthmonitoring-90af9.firebasestorage.app',
    iosBundleId: 'com.example.jointHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzAZj8Kbj74nycnTiiRHRmlZBNRILy5kE',
    appId: '1:555705912730:ios:f5c0a0d2b096de63bffe23',
    messagingSenderId: '555705912730',
    projectId: 'healthmonitoring-90af9',
    storageBucket: 'healthmonitoring-90af9.firebasestorage.app',
    iosBundleId: 'com.example.jointHealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOqFdCftAcLo095PrfAPpz_IaTsEdzkeQ',
    appId: '1:555705912730:web:9cf1f79a5379bc5dbffe23',
    messagingSenderId: '555705912730',
    projectId: 'healthmonitoring-90af9',
    authDomain: 'healthmonitoring-90af9.firebaseapp.com',
    storageBucket: 'healthmonitoring-90af9.firebasestorage.app',
    measurementId: 'G-YD10X121CL',
  );
}
